### ISSUE TITLE
write spin-free 1- and 2-rdm to output file

### ISSUE THREAD

**Issue by edeprince3** [edeprince3/v2rdm_casscf#15]
Add flag to write spin-free 1- and 2-RDM to output file.

**Comment by cuanto** [comment]
Hi, 

I have a simple approach for doing it, but I have some problems with the index, I attach the code. It is a simple call to WriteTPM and then using the code in ReadTPM I make a new routine that read and sum spin parts. Values appear to be good, and Trace of 1-RDM and 2-RDM sum to correct values, and the energy is well reproduced.

Running the attached example for N2 I get for the 1-RDM 

0 0 2.00000000
1 1 2.00000000
2 2 1.99611689
8 8 0.00847917
11 11 0.00848009
15 15 2.00000000
16 16 2.00000000
17 17 0.00324298
22 22 1.99184149
25 25 1.99184188

From the chemical point of view I think that high orbitals should not display populations like 1.99184149.

I have some problems uploading files, so i shared it in dropbox.

https://www.dropbox.com/s/49dnvbit1pad5fu/example-and-code.zip?dl=0

**Comment by edeprince3** [comment]
What you're seeing is the result of the orbital ordering we've chosen.  The orbitals are not ordered by energy.  They are ordered first by irreducible representation and then by energy within each irrep.  If you search in the output file for "Pre-Iterations" you will find the total number of orbitals in each irrep.  Inside the c code, the arrays nmopi_ or nsopi_ give you the number of orbitals per irrep in the MO or SO basis.

**Comment by cuanto** [comment]
Thanks, I will try during this week to print it in an ordered format, to match for example the order in the molden file, hope this order will serve for future canonical orbitals option, as I am new to c++ , it is not trivial for me.

Again thanks your patience and time.

**Comment by edeprince3** [comment]
I am closing this because I can't recall why I wanted the spin-free RDMs in the first place.  Several functions exist not to write the spin blocks in a couple of different formats.
