### ISSUE TITLE
LICENSE says GPLv3, but copyright boilerplate in source say GPLv2

### ISSUE THREAD

**Issue by mbanck** [edeprince3/v2rdm_casscf#18]
Minor thing, but there's a discrepancy between the content of ```LICENSE``` and the (auto-generated) copyright headers in the source files: the former says GPLv3, while the latter say GPLv2+. Technically GPLv2 (or any later version) includes GPLv3, but it might make sense to clarify that.

**Comment by loriab** [comment]
hear, hear, just found this, too. Which do you want, Eugene? I'll fix it up.
