### ISSUE TITLE
A test project with v2rdm_casscf

### ISSUE THREAD

**Issue by MThomasRed92** [edeprince3/v2rdm_casscf#22]
Hi,

I am curious how v2RDM-CASSCF works and I did a test project inspired by the work of G. Chan.
http://aip.scitation.org/doi/pdf/10.1063/1.3275806

Basically, I want to calculate the isomerization energy of two isomers of Cu2O2. The active space is 28 electrons in 32 orbitals. The basis set is small. The molecule has D2h symmetry. Thus I think that it is feasible.
The reference result from DMRG is 25.6 kcal/mol.

This is an input file

```
sys.path.insert(0, '/temp0/tm/source')
import v2rdm_casscf
memory 120 Gb

molecule bis {
Cu 0.00  0.00 0.00
Cu 0.00  0.00 2.80
O  0.00  1.15 1.40
O  0.00 -1.15 1.40

2 1
units ang
}

basis mybas{
  assign Cu stuttgart
  assign O  roos-ano-dz
}

set globals{
  basis mybas
  reference rhf
  scf_type cd
  df_ints_io     save
  cholesky_tolerance 1.0e-4
#             Ag   B1g   B2g   B3g    Au   B1u   B2u   B3u 
  restricted_docc [ 4, 1, 0, 1, 0, 1, 2, 3]
  active          [ 6, 4, 4, 2, 2, 4, 6, 4]
       
  mcscf_maxiter 200
  nat_orbs true
  diis_max_vecs 20
  die_if_not_converged false
  print_mos true
}

scf_e, wfn = energy('b3lyp', return_wfn=True)
molden(wfn, 'b3lyp.molden')

set v2rdm_casscf {
  positivity                DQG
  r_convergence             1e-4
  e_convergence             1e-4
  maxiter                   10000
  constrain_d3              false
  write_checkpoint_file     true
  cholesky_tolerance        1e-4
  molden_write              true
  orbopt_write              true
}

cas_e, cas_wfn = energy('v2rdm-casscf', return_wfn=True)
```

Since maxiter is only 10000, the calculation crashed because v2RDM-CASSCF not converge.
The intriguing thing is that at the iteration 10000, the isomerization energy is only -0.8 kcal/mol. This error is huge and I don't know what causes this:
- It can be the poor initial active space, but I cannot find a way to manually choose it, by e.g. reading DFT or HF orbitals and rotate them. Is there any keyword to do this?
- In the end, there is no way I can check how the active space looks like.
- DQG+T2 should produce better results, but it is extremely slow and I gave up this calculation.

Thanks!

**Comment by edeprince3** [comment]
Just so you know, I'm not ignoring your question.  I have a student running some tests with your on this system before responding in full.  

Regarding the number of iterations, just increase maxiter.  We ran tests with a (28,32) active space (and a different basis than what you're using), and the code required 20 or 30K iterations.

I'm not sure what you mean about not controlling the active space.  The options restricted_docc and active give you control over what orbitals go into the active space.  If you want to know what the orbitals look like, run the Hartree-Fock and ask psi4 to print a molden file.

If you want different starting orbitals, you can do something like:

en,wfn = energy('b3lyp',return_wfn=True)
energy('v2rdm-casscf',ref_wfn=wfn)

Regarding DQGT2, the current code for the T2 conditions is not optimized and is too slow for a job this size.

**Comment by MThomasRed92** [comment]
Hi,

Thank you for your answer.
What I mean "controlling the active space" is an ability to specify which orbital should be in the active space at the beginning of the calculation.
Using ref_wfn is fine, but not really enough since the program automatically chooses active orbitals around the HOMO and LUMO. In many cases, these orbitals are not the one we need in the active space and the calculation can easily converges to an undesirable active space.

In DETCI for example we have MCSCF_ROTATE
http://www.psicode.org/psi4manual/1.1/autodoc_glossary_options_c.html#term-mcscf-rotate-detci

In Forte, we have ROTATE_MOS

Thanks.

**Comment by edeprince3** [comment]
OK, whenever I have some time, I'll add  MCSCF_ROTATE to match DETCIs functionality.

**Comment by edeprince3** [comment]
Well, I'm embarrassed that it took a year to resolve this, but @rainli323 just checked in the code for MCSCF_ROTATE.  You can find a sample input in tests/v2rdm7.  I'm going to go ahead and close this issue, but please reopen it or open a new ticket if you need something else.
