### ISSUE TITLE
flags to print 2-, 3-RDM

### ISSUE THREAD

**Issue by edeprince3** [edeprince3/v2rdm_casscf#7]
Other modules might eventually want to use the 2-RDM (or 3-RDM).  We need input options and code to do this.

**Comment by cuanto** [comment]
Hello,

I am interested in the 1-RDM and 2-RDM, for integrating it over QTAIM domains, for my code  I need two files one molden file with canonical orbitals (still need to read more in the code on how to print canonical orbitals instead natural orbitals) and another file with the 1 and 2 RDM, in the following format

The 1-RDM is:
i j value 
....
The 2-RDM is:
i j k l value
....

I read the file write_tpdm.cc, I think I can use it as a template and contract the 2-RDM to obtain the 1-RDM, but it is the total spin free 1-RDM and 2-RDM stored in some variable ? so I can avoid to add spin parts and the differents parts core-core/core-active/active-active.

**Comment by edeprince3** [comment]
I will open a new ticket to print molecular orbitals and natural orbitals.  I will take care of that soon.  Note that the molecular orbitals will be different than Hartree-Fock canonical molecular orbitals.  

Regarding the 1- and 2-RDM, no, I don't store or write the total spin-free 1- and 2-RDM anywhere.  you can use the write_tpdm_full flag (that I will check in soon) to write the full 2-RDM by block in the format given in write_tpdm.cc ( value p q r s ) where pq; rs correspond to electrons 12;12:

D2(pq;rs) = < p*q*sr > 

This feature was actually meant for internal use in Psi4, and the files are written in binary.  You would need to tell psi4 to save the file in your input file as:

psioh = psi4.IOManager.shared_object()
psioh = set_specific_retention(XXX,true), where XXX = 270,271,272 

(look in v2rdm_solver.h for which file is which)

Eventually, I will find time to write the spin-free 1-RDM and 2-RDM in human-readable text

**Comment by edeprince3** [comment]
The original intent of this ticket has been resolved.  The new issues are in new tickets.
